contentitemexportablefields:
  contentitemfields:
    propagationLabels:
    - all
id: SENTRIA - M - Sentria App Quick Actions
inputs: []
name: SENTRIA - M - Sentria App Quick Actions
outputs: []
starttaskid: "0"
tags:
- SENTRIA
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 7d5be0d1-1635-4261-8aef-8eecbf61e73c
      iscommand: false
      name: ""
      version: -1
      description: ''
    taskid: 7d5be0d1-1635-4261-8aef-8eecbf61e73c
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 695,
          "y": 50
        }
      }
  "1":
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: commands.local.cmd.close.inv
      id: f0f2dd3f-6145-4a35-9c09-24ed3e389bdd
      iscommand: true
      name: Close investigation
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: f0f2dd3f-6145-4a35-9c09-24ed3e389bdd
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 695,
          "y": 550
        }
      }
  "2":
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: fb0d765f-05af-4b60-8208-b0570510a812
      iscommand: false
      name: Done
      type: title
      version: -1
      description: ''
    taskid: fb0d765f-05af-4b60-8208-b0570510a812
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 695,
          "y": 720
        }
      }
  "3":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: incident.sentriaappaction
          operator: isEqualString
          right:
            value:
              simple: scan_hostname
      label: SCAN HOSTNAME
    - condition:
      - - left:
            iscontext: true
            value:
              simple: incident.sentriaappaction
          operator: isEqualString
          right:
            value:
              simple: block_ioc
      label: BLOCK IOC
    - condition:
      - - left:
            iscontext: true
            value:
              simple: incident.sentriaappaction
          operator: isEqualString
          right:
            value:
              simple: contact_analyst
      label: CONTACT ANALYST
    continueonerrortype: ""
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "7"
      BLOCK IOC:
      - "5"
      CONTACT ANALYST:
      - "6"
      SCAN HOSTNAME:
      - "4"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 82e4f14b-c5d2-438b-a99a-d27aa94ceaf7
      iscommand: false
      name: Action to be executed
      type: condition
      version: -1
    taskid: 82e4f14b-c5d2-438b-a99a-d27aa94ceaf7
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 695,
          "y": 210
        }
      }
  "4":
    continueonerrortype: ""
    id: "4"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    scriptarguments:
      value:
        simple: SCAN HOSTNAME
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Prints text to war room (Markdown supported)
      id: a0b9079d-d251-466f-b3cf-1b57770270cb
      iscommand: false
      name: Scan Hostname
      scriptName: Print
      type: regular
      version: -1
    taskid: a0b9079d-d251-466f-b3cf-1b57770270cb
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 380
        }
      }
  "5":
    continueonerrortype: ""
    id: "5"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    scriptarguments:
      value:
        simple: BLOCK IOC
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Prints text to war room (Markdown supported)
      id: 458ad16a-eb0a-43b8-9115-24ff405ed19a
      iscommand: false
      name: Block IOC
      scriptName: Print
      type: regular
      version: -1
    taskid: 458ad16a-eb0a-43b8-9115-24ff405ed19a
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 480,
          "y": 380
        }
      }
  "6":
    continueonerrortype: ""
    id: "6"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    scriptarguments:
      value:
        simple: CONTACT ANALYST
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Prints text to war room (Markdown supported)
      id: de6ada81-0dbb-457a-a170-6224fc69a556
      iscommand: false
      name: Contact Analyst
      scriptName: Print
      type: regular
      version: -1
    taskid: de6ada81-0dbb-457a-a170-6224fc69a556
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 910,
          "y": 380
        }
      }
  "7":
    continueonerrortype: ""
    id: "7"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 24c42ea6-1f52-4fca-88d8-e9567329bd3e
      iscommand: false
      name: Do Nothing
      type: title
      version: -1
      description: ''
    taskid: 24c42ea6-1f52-4fca-88d8-e9567329bd3e
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 1340,
          "y": 385
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 730,
        "width": 1670,
        "x": 50,
        "y": 50
      }
    }
  }
tests:
- No tests (auto formatted)
fromversion: 6.0.0
